language: go
env:
  global:
  - DEP_VERSION=0.5.4
before_install:
- curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64
  -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep
- go get -u github.com/go-bindata/go-bindata/...
go:
- 1.13.5
- master
before_deploy:
- dep ensure && go generate
- GOOS=darwin GOARCH=amd64 go build -o bin/dd2tf-darwin-amd64
- GOOS=linux GOARCH=amd64 go build -o bin/dd2tf-linux-amd64
deploy:
  provider: releases
  api_key:
    secure: mr2XfYKTeH0EE1zdG++D9GIZFC/gVi/0L90uIOGitfHZ8lqQOXbPzdhosoQBxl8CgK5XVpRe7z5WqGYjhff3SNxYiy/WzUAPyItLemo5Urnr5tV7dyjtMT2EE71lmBAJ1rMZTBrOk1uA08m2eXNW5rz+4ZvaoPZBXkDcE7rVzjBRi13IQGWzn5c2NkmPgUxPjjbhzCEJzKuSnnTo1Rs98t5OuVag5QV08bOlNbGkeQXYBE6LcLPZqi3bXkFbAoqU+1bWU7mZXxxoCopyn7RKCa+06B+RTMwjqTQeSaktMSnuAM+FUMjLiqD6myqW2s4FBKhVd4VAlxYMDJ2gZ/YYBlAvwFLDwc4uwrTFpwdyH8cSYybof+BXAsGDrlMVXZhvylftyri79XlYN/VW9waTEWSTn4wJB8jeC7YW6GYdUbfkNxtvbH4a6vPtPkZyo+MECaHfkco18GfQfRGjtPcW8ct3pwZoXo+DJWPxZ/Y5JOQibW0Dka97vLM2GM6OvrORFSrEY4lNgMQVwWwBI7tSKAF8vgUqnCGGZ1YHFJBF4USi7I1Aqs7a1bD+M4cvBk9oJS/YKcGgw2QxzH7prttMBV+ssFShuC+BIhbjWGRAnUolNbb5yIAs8ZrN+q8JLGEda4YHiSHuoSGYR1wLfONWRyKvSWjxeLAyt5XRdLHEobI=
  file:
  - bin/dd2tf-darwin-amd64
  - bin/dd2tf-linux-amd64
  on:
    repo: toozej/dd2tf
    tags: true
    branch: master
    go: 1.13.5
  skip-cleanup: true
