language: go
env:
  global:
  - DEP_VERSION=0.5.4
before_install:
- curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64
  -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep
- go get -u github.com/go-bindata/go-bindata/...
go:
- 1.13.5
- master
before_deploy:
- dep ensure && go generate
- GOOS=darwin GOARCH=amd64 go build -o bin/dd2tf-darwin-amd64
- GOOS=linux GOARCH=amd64 go build -o bin/dd2tf-linux-amd64
deploy:
  provider: releases
  api_key:
    secure: hRJ4FXY4uX4Y6UXelMB7LpoSkoWEAmsnwyMnRWNike3BTvnNY/lGw+XHj/gmBT6BYis8a4zM6NSlBvhiGmAWjTM1IBikq9X26Td54JRIX3oCTF0i0tWGXN662heKu5WWzTpPtFKvSfFeSSN41MxH4ME6dUMUXR02QtbOvMsWsfZQ2bdWTXB06jTYpGFkIPjHIjzqxkVnE3D7sjeK5x5/nQco1zTQjA8BkAiasaoF8JC1H5wdCpAsMP8yd1e3H6a5AFShD1elPxT4kVi3RKLylN2NPDlcuI+lkxajBTThDK5Iyfyuj6feSHorpoWbjVlkMlfTFS4cb579DEpe70WTnqYVqXX1Mzvh96DX88CBlLohfXkY2o7YidS+yUJd1e/YzNdQPaWe7tyAAvEB53i2vf6Y//tkWJO3+cv9mzzj7jS8JbJRykM9dHTE/nqqaYfZObN/hZuG+7njeXyZfrVV+MDdKW6bnefrmM3K1nXjqBfLMSPBJ0Zm7KOfYYgWJgZCjDzyW24rGDT+UbW2zxsBVUo+pTdqDQWFWnQON3aqfrYJyhmXK8iKXvlrMmpHg3a7H1O5az8dxSuSYMIOmkdsdjPlsjiPfcbvgYuOE2gnMlgLV1jx9eHc7TE9G31jKH/QL63OUPhXlOv43R8LPKV1ayNZeckAAMjw3ydtGoC0Gc4=
  file:
  - bin/dd2tf-darwin-amd64
  - bin/dd2tf-linux-amd64
  on:
    repo: toozej/dd2tf
    tags: true
    branch: master
    go: 1.13.5
  skip-cleanup: true
